import requests
import os
import random
import sys
import time
import yfinance as yf
import matplotlib.pyplot as plt
import pandas as pd
from datetime import datetime
from huggingface_hub import InferenceClient

# --- CONFIGURATION ---
LINKEDIN_TOKEN = os.environ["LINKEDIN_ACCESS_TOKEN"]
GEMINI_API_KEY = os.environ["GEMINI_API_KEY"]
HF_TOKEN = os.environ["HUGGINGFACE_TOKEN"]

# --- 1. THE ARTIST (AI Image Generator) ---
def generate_image(prompt):
    """Generates an AI image using Flux or Stable Diffusion (Free via HF)."""
    print(f"🎨 Painting image for: {prompt}")
    client = InferenceClient(token=HF_TOKEN)
    
    # Using a fast, free model on Hugging Face
    try:
        image = client.text_to_image(
            prompt=f"professional tech illustration, minimal, futuristic, 8k resolution: {prompt}",
            model="black-forest-labs/FLUX.1-schnell" # Top tier open model
        )
        image_path = "post_image.png"
        image.save(image_path)
        print("✅ Image saved.")
        return image_path
    except Exception as e:
        print(f"⚠️ Image generation failed: {e}")
        return None

# --- 2. THE WALL STREET ANALYST (Finance Charts) ---
def generate_market_chart(ticker):
    """Fetches stock data and draws a chart."""
    print(f"📈 Analyzing market data for {ticker}...")
    stock = yf.Ticker(ticker)
    hist = stock.history(period="5d") # Last 5 days
    
    if hist.empty:
        return None

    # Create Chart
    plt.figure(figsize=(10, 5))
    plt.plot(hist.index, hist['Close'], marker='o', linestyle='-', color='#0077b5') # LinkedIn Blue
    plt.title(f"{ticker} - Last 5 Days Performance")
    plt.grid(True, which='both', linestyle='--', linewidth=0.5)
    plt.savefig("chart.png")
    plt.close()
    print("✅ Chart generated.")
    return "chart.png"

# --- 3. THE BRAIN (Gemini 2.5) ---
def generate_text(mode, topic):
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={GEMINI_API_KEY}"
    
    prompts = {
        "FINANCE": f"Write a LinkedIn post about {topic}'s current market movement. Be analytical. Mention 'Market Update'. End with a question.",
        "TECH": f"Write a LinkedIn post about this tech concept: {topic}. Make it sound visionary. Use short sentences.",
        "MOTIVATION": f"Write a short, punchy career advice post about: {topic}. Don't be cringe. Be real."
    }
    
    prompt = f"{prompts[mode]} STRICT: Output ONLY the post text. No intro. Add 3 tags."
    
    payload = {"contents": [{"parts": [{"text": prompt}]}]}
    response = requests.post(url, json=payload)
    if response.status_code == 200:
        return response.json()['candidates'][0]['content']['parts'][0]['text']
    return None

# --- 4. THE PUBLISHER (LinkedIn API with Image Support) ---
def register_image(urn, image_path):
    """Step 1: Tell LinkedIn we want to upload an image."""
    url = "https://api.linkedin.com/v2/assets?action=registerUpload"
    headers = {"Authorization": f"Bearer {LINKEDIN_TOKEN}"}
    
    payload = {
        "registerUploadRequest": {
            "recipes": ["urn:li:digitalmediaRecipe:feedshare-image"],
            "owner": urn,
            "serviceRelationships": [{"relationshipType": "OWNER", "identifier": "urn:li:userGeneratedContent"}]
        }
    }
    
    res = requests.post(url, headers=headers, json=payload).json()
    upload_url = res['value']['uploadMechanism']['com.linkedin.digitalmedia.uploading.MediaUploadHttpRequest']['uploadUrl']
    asset_urn = res['value']['asset']
    
    # Step 2: Upload the actual file
    with open(image_path, "rb") as file:
        requests.put(upload_url, headers={"Authorization": f"Bearer {LINKEDIN_TOKEN}"}, data=file)
        
    return asset_urn

def post_with_media(urn, text, image_path):
    asset_urn = register_image(urn, image_path)
    
    url = "https://api.linkedin.com/v2/ugcPosts"
    headers = {"Authorization": f"Bearer {LINKEDIN_TOKEN}", "X-Restli-Protocol-Version": "2.0.0"}
    
    payload = {
        "author": urn,
        "lifecycleState": "PUBLISHED",
        "specificContent": {
            "com.linkedin.ugc.ShareContent": {
                "shareCommentary": {"text": text},
                "shareMediaCategory": "IMAGE",
                "media": [{"status": "READY", "description": {"text": "Generated by AI"}, "media": asset_urn, "title": {"text": "Visual Insight"}}]
            }
        },
        "visibility": {"com.linkedin.ugc.MemberNetworkVisibility": "PUBLIC"}
    }
    
    res = requests.post(url, headers=headers, json=payload)
    if res.status_code == 201:
        print("✅ SUCCESS! Image Post is Live.")
    else:
        print(f"❌ Failed: {res.text}")

def get_user_urn():
    url = "https://api.linkedin.com/v2/userinfo"
    headers = {"Authorization": f"Bearer {LINKEDIN_TOKEN}"}
    res = requests.get(url, headers=headers).json()
    return f"urn:li:person:{res['sub']}"

# --- MAIN EXECUTION ---
if __name__ == "__main__":
    urn = get_user_urn()
    
    # Randomly choose a "Department" to run
    MODE = random.choice(["FINANCE", "TECH", "MOTIVATION"])
    
    if MODE == "FINANCE":
        # Pick a random tech stock or crypto
        ticker = random.choice(["NVDA", "GOOGL", "MSFT", "BTC-USD", "ETH-USD"])
        chart_file = generate_market_chart(ticker)
        post_text = generate_text(MODE, ticker)
        post_with_media(urn, post_text, chart_file)
        
    elif MODE == "TECH":
        topic = random.choice(["Agentic AI", "Quantum Computing", "Rust vs Python", "Cloudflare Architecture"])
        # Generate cool AI art
        img_file = generate_image(f"futuristic concept art of {topic}, abstract, cyan and purple lighting")
        post_text = generate_text(MODE, topic)
        if img_file:
            post_with_media(urn, post_text, img_file)
            
    elif MODE == "MOTIVATION":
        topic = random.choice(["Deep Work", "Imposter Syndrome", "Consistency", "Learning to Code"])
        # Generate minimalist art
        img_file = generate_image(f"minimalist vector art representing {topic}, clean lines, pastel colors")
        post_text = generate_text(MODE, topic)
        if img_file:
            post_with_media(urn, post_text, img_file)
